### ISSUE TITLE
Where can one get inf-template.el?

### ISSUE THREAD

**Issue by tarsius** [brantou/ob-coffeescript#1]
I maintain the [Emacsmirror](https://emacsmirror.net) and as part of that effort I try to make sure that the dependencies of all mirrored packages can be satisfied. Where can I get `inf-template.el` from?

**Comment by brantou** [comment]
I have not quoted any *inf-template.el*, so what you want is *ob-tmplate.el*.  If you want 
 *ob-tmplate.el* , you can get this from http://orgmode.org/w/worg.git/blob/HEAD:/org-contrib/babel/ob-template.el.

**Comment by tarsius** [comment]
[Here](https://github.com/brantou/ob-coffeescript/blob/master/ob-template.el#L71) you require it. By the way, that file is corrupted - the first 59 lines begin with line numbers.

**Comment by tarsius** [comment]
... in a copy of `ob-template.el` that is. It's not a good idea to bundle dependencies, because they tend to not get updated (and in this case corrupted :wink:) and there is always the risk that for some users (those that don't use `package.el`) the obsolete bundled version gets loaded instead of the updated upstream version.

**Comment by brantou** [comment]
Thanks for pointing out my miss.  *ob-template.el* has been deleted.

**Comment by tarsius** [comment]
Thanks a lot!
